apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls
  namespace: argocd
spec:
  secretName: argocd-tls
  dnsNames:
    - argocd.apps.example.lan
  issuerRef:
    name: homelab-ca
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-tls
  namespace: keycloak
spec:
  secretName: keycloak-tls
  dnsNames:
    - auth.apps.example.lan
  issuerRef:
    name: homelab-ca
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitea-tls
  namespace: gitops-gitea
spec:
  secretName: gitea-tls
  dnsNames:
    - git.apps.example.lan
  issuerRef:
    name: homelab-ca
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ceph-dashboard-sso-tls
  namespace: rook-ceph
spec:
  secretName: ceph-dashboard-sso-tls
  dnsNames:
    - ceph.apps.example.lan
  issuerRef:
    name: homelab-ca
    kind: ClusterIssuer
    group: cert-manager.io
