apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-platform-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  project: default
  source:
    repoURL: https://github.com/CHANGE_ME/talos-argocd-metallb-gitops.git
    targetRevision: main
    path: argocd/platform-config
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
