apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph-cluster
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  project: default
  sources:
    - repoURL: https://charts.rook.io/release
      chart: rook-ceph-cluster
      targetRevision: 1.20.1
      helm:
        releaseName: rook-ceph-cluster
        valueFiles:
          - $values/infrastructure/rook-ceph-cluster/values.yaml
    - repoURL: https://github.com/CHANGE_ME/talos-argocd-metallb-gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
