apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-certificates
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "55"
spec:
  project: default
  source:
    repoURL: https://github.com/Sebastian-Nowaczyk-Elektrorecykling/metallb-ingress.git
    targetRevision: main
    path: infrastructure/certificates
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
