apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "70"
spec:
  project: default
  sources:
    - repoURL: registry-1.docker.io/bitnamicharts
      chart: keycloak
      targetRevision: 25.2.0
      helm:
        releaseName: keycloak
        valueFiles:
          - $values/platform/keycloak/values.yaml
    - repoURL: https://github.com/Sebastian-Nowaczyk-Elektrorecykling/metallb-ingress.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
