apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea-db
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "80"
spec:
  project: default
  source:
    repoURL: https://github.com/Sebastian-Nowaczyk-Elektrorecykling/metallb-ingress.git
    targetRevision: main
    path: platform/gitea-db
  destination:
    server: https://kubernetes.default.svc
    namespace: gitops-gitea
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
