apiVersion: v1
kind: Secret
metadata:
  name: repo-bitnami-oci
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: bitnami-oci
  type: helm
  url: registry-1.docker.io/bitnamicharts
  enableOCI: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: repo-gitea-charts
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: gitea-charts
  type: helm
  url: https://dl.gitea.com/charts/
---
apiVersion: v1
kind: Secret
metadata:
  name: repo-oauth2-proxy
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: oauth2-proxy
  type: helm
  url: https://oauth2-proxy.github.io/manifests
